export const INCREASE_PAGE = "INCREASE_PAGE";
export const DECREASE_PAGE = "DECREASE_PAGE";

// PERSONAL INFO TYPES
export const SET_FIRSTNAME = "SET_FIRSTNAME";
export const SET_LASTNAME = "SET_LASTNAME";
export const SET_EMAIL = "SET_EMAIL";

// COVID INFO TYPES
export const SET_HADCOVID = "SET_HADCOVID";
export const SET_ANTIBODY_TEST = "SET_ANTIBODY_TEST";
export const SET_ANTIBODY_NUMBER = "SET_ANTIBODY_NUMBER";
export const SET_ANTIBODY_DATE = "SET_ANTIBODY_DATE";
export const SET_HADCOVID_DATE = "SET_HASCOVID_DATE";

// VACCINATION INFO TYPES
export const SET_ISVACCINATED = "SET_ISVACCINATED";
export const SET_VACCINATIONDOSE = "SET_VACCINATIONDOSE";
export const SET_WAITING_FOR = "SET_WAITING_FOR";

// RECCOMENDATION INFO TYPES
export const SET_ONLINE_MEETINGS = "SET_ONLINE_MEETINGS";
export const SET_OFFICE_WORK_DAYS = "SET_OFFICE_WORK_DAYS";
export const SET_PHYSICAL_MEETINGS = "SET_PHYSICAL_MEETINGS";
export const SET_OPINION_ABOUT_ENV = "SET_OPINION_ABOUT_ENV";