export const INCREASE_PAGE = "INCREASE_PAGE";
export const DECREASE_PAGE = "DECREASE_PAGE";

export const SET_FIRSTNAME = "SET_FIRSTNAME";
export const SET_LASTNAME = "SET_LASTNAME";
export const SET_EMAIL = "SET_EMAIL";

export const SET_FIRSTNAME_ERR = "SET_FIRSTNAME_ERR";
export const SET_LASTNAME_ERR = "SET_LASTNAME_ERR";
export const SET_EMAIL_ERR = "SET_EMAIL_ERR";