export const INCREASE_PAGE = "INCREASE_PAGE";
export const DECREASE_PAGE = "DECREASE_PAGE";

// COVID INFO TYPES
export const SET_ANTIBODY_TEST = "SET_ANTIBODY_TEST";
export const SET_ANTIBODY_NUMBER = "SET_ANTIBODY_NUMBER";
export const SET_ANTIBODY_DATE = "SET_ANTIBODY_DATE";
export const SET_HADCOVID_DATE = "SET_HASCOVID_DATE";

// VACCINATION INFO TYPES
export const SET_VACCINATIONDOSE = "SET_VACCINATIONDOSE";
export const SET_WAITING_FOR = "SET_WAITING_FOR";

// SETTING VALUE TYPE
export const SET_VALUE = "SET_VALUE";